### ISSUE TITLE
About the visual feature extraction.

### ISSUE THREAD

**Issue by EstherBear** [fpsluozi/tofindwaldo#1]
Hi, could you provide a link for your extracted visual features?

I've extracted the image features from bounding boxes with this [repo](https://github.com/MILVLG/bottom-up-attention.pytorch), but it resulted in NaN when I used these features to train. 

Thanks!

**Comment by fpsluozi** [comment]
Hi there.

Sorry I was on some other project this summer and missed your inquiry. I reckon you've already figured this out?

If not, you will have to use the `--extract-mode bbox_feats` mode while using the Pytorch repo. You will have to save the Who's Waldo original's given bounding boxes into individual .npz files first.

What I used looks like this in the end 

`# python3 waldo_extract_features_faster.py --mode caffe --num-cpus 0 --gpu '0,1,2' --extract-mode bbox_feats --config-file configs/bua-caffe/extract-bua-caffe-r101.yaml --image-dir /beegfs/yluo97/waldo/img --out-dir /beegfs/yluo97/waldo/img_roi_npz_new --bbox-dir /beegfs/yluo97/waldo/bboxes_npz_new --resume `

Let me know if you need any more help tho

**Comment by EstherBear** [comment]
> Hi there.
> 
> Sorry I was on some other project this summer and missed your inquiry. I reckon you've already figured this out?
> 
> If not, you will have to use the `--extract-mode bbox_feats` mode while using the Pytorch repo. You will have to save the Who's Waldo original's given bounding boxes into individual .npz files first.
> 
> What I used looks like this in the end
> 
> `# python3 waldo_extract_features_faster.py --mode caffe --num-cpus 0 --gpu '0,1,2' --extract-mode bbox_feats --config-file configs/bua-caffe/extract-bua-caffe-r101.yaml --image-dir /beegfs/yluo97/waldo/img --out-dir /beegfs/yluo97/waldo/img_roi_npz_new --bbox-dir /beegfs/yluo97/waldo/bboxes_npz_new --resume `
> 
> Let me know if you need any more help tho

Thank you for your reply! I've sucessfully extracted the features.
