### ISSUE TITLE
About max_txt_len.

### ISSUE THREAD

**Issue by EstherBear** [fpsluozi/tofindwaldo#2]
May I ask if your implementation, when training and testing, filters out examples with text length >100?
Are the results you report in your paper based on this implementation?

**Comment by fpsluozi** [comment]
Hi there. As far as I can remember we used a max length of 160, and the program would automatically cap the caption length to the max length by ditching the exceeding tokens.

**Comment by EstherBear** [comment]
> Hi there. As far as I can remember we used a max length of 160, and the program would automatically cap the caption length to the max length by ditching the exceeding tokens.

Thank you for your reply. 
But if you use the source code of the original Who's Waldo work, you will just filter out examples with text length larger than the max length you set. 
FYI, you can find the details here. https://github.com/clairecyq/whos-waldo/blob/26e6ea7760bceeddde5ec3346af493be32234010/data/data.py#L188

**Comment by fpsluozi** [comment]
> 

You're right.

I don't recall the details from our best runs but we did try out the original max_len and our larger max_len. The difference was not that significant.

The trade-off is that using a smaller cap length would ditch potentially more samples while training, while using a larger cap length would introduce more pad tokens. There could be potentials for improvements anyways.

**Comment by EstherBear** [comment]
Thank you for your reply.

In the source code, the training and inferring use the same configuration (and thus same max_len). So may I ask if the accuracy of test set reported in the paper didn't include the examples in the test set with text length larger than the max_len?

**Comment by fpsluozi** [comment]
> 

Nope the paper did not include those that exceed max_len.

**Comment by EstherBear** [comment]
> > 
> 
> Nope the paper did not include those that exceed max_len.

Thank you for your reply. I will close this issue.
